config/routes.rb
Rails.application.routes.draw do
  root to: 'speed_tests#new'

  resources :speed_tests
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/speed_test.rb
class SpeedTest < ApplicationRecord
  validates_presence_of :email
  validates_presence_of :url
  validates :url, http_url: true

  def url=(value)
    return super unless value.present?

    return super if value.start_with?('http://') || value.start_with?('https://')

    super("http://#{value}")
  end

  def status_text
    return 'Fetching website' if gtmetrix_test_id.blank?

    return 'Analyzing critical metrics' if gtmetrix_report_id.blank?

    return 'Generating report' if gtmetrix_report_data.blank?

    return 'Done!'
  end

  def done?
    gtmetrix_report_data.present?
  end

  def continue_process
    return if done?
    return if gtmetrix_test_id.blank?

    ContinueSpeedTestJob.perform_later(id, 'get_report_id') and return if gtmetrix_report_id.blank?

    ContinueSpeedTestJob.perform_later(id, 'report_url') and return if gtmetrix_report_url.blank?

    ContinueSpeedTestJob.perform_later(id, 'report') and return if gtmetrix_report_data.blank?
  end

  def start
    return if gtmetrix_test_id

    response = execute("https://gtmetrix.com/api/2.0/tests", JSON.dump({
      "data" => {
        "type" => "test",
        "attributes" => {
          "url" => url,
          "adblock" => 1
        }
      }
    }))

    return unless response.kind_of? Net::HTTPSuccess

    res = JSON.parse(response.body)
    test_id = res.dig('data', 'id')
    update! gtmetrix_test_id: test_id if test_id.present?
    ContinueSpeedTestJob.perform_later(id, 'get_report_id')
  end

  def get_report_id
    return unless gtmetrix_test_id

    response = execute("https://gtmetrix.com/api/2.0/tests/#{gtmetrix_test_id}", nil, method: :get)

    return unless response.kind_of? Net::HTTPRedirection

    res = JSON.parse(response.body)
    report_id = res.dig('data', 'links', "report").split("/").last
    update! gtmetrix_report_id: report_id if report_id.present?
    ContinueSpeedTestJob.perform_later(id, 'report_url')
  end

  def report_url
    return gtmetrix_report_url if gtmetrix_report_url.present?
    return unless gtmetrix_test_id
    return unless gtmetrix_report_id

    response = execute("https://gtmetrix.com/api/2.0/reports/#{gtmetrix_report_id}", nil, method: :get)

    return unless response.kind_of? Net::HTTPSuccess

    res = JSON.parse(response.body)
    update! gtmetrix_report_url: res.dig("data", "links", "report_pdf")
    ContinueSpeedTestJob.perform_later(id, 'report')
  end

  def report
    return unless gtmetrix_test_id
    return unless gtmetrix_report_id

    response = execute(report_url, nil, method: :get)

    case response
    when Net::HTTPSuccess then
      update!(gtmetrix_report_data: response.body)
    when Net::HTTPRedirection then
      location = "https://gtmetrix.com#{response['location']}"
      warn "redirected to #{location}"
      redirect_response = execute(location, nil, method: :get)
      return unless redirect_response.kind_of? Net::HTTPSuccess
      update!(gtmetrix_report_data: redirect_response.body)
      # File.binwrite("thepdf.pdf", redirect_response.body)
    else
      # Prob some error
    end
  end

  private

  def execute(endpoint, body, method: :post)
    uri = URI.parse(endpoint)
    request = method == :post ? Net::HTTP::Post.new(uri) : Net::HTTP::Get.new(uri)
    request.basic_auth("0369426ab630d3914d706027a3d1051c", "")
    request.content_type = "application/vnd.api+json" if body
    request.body = body if body

    req_options = {
      use_ssl: uri.scheme == "https",
    }

    response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
      http.request(request)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/speed_tests_controller.rb
class SpeedTestsController < ApplicationController
  protect_from_forgery except: :show

  def new
    @speed_test = SpeedTest.new
  end

  def show
    @speed_test = SpeedTest.find(params[:id])

    @speed_test.continue_process

    respond_to do |format|
      format.html
      format.js
      format.pdf { send_data @speed_test.gtmetrix_report_data, filename: 'MAKO Quick Performance Report.pdf' }
    end
  end

  def create
    @speed_test = SpeedTest.new(speed_test_params)
    if @speed_test.save
      ContinueSpeedTestJob.perform_later(@speed_test.id, 'start')
      render
    else
      render 'error'
    end
  end

  private

  def speed_test_params
    params.require(:speed_test).permit(:url, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/speed_tests/_form.html.erb
<%= form_with model: @speed_test, local: false, html: { id: 'main-form', class: 'wpcf7-form init xs-home-light9-form xs-home-10-form' } do |form| %>
  <div class="row">
    <div class="col-lg-6 xs-mb-4">
      <span class="wpcf7-form-control-wrap your-name">
        <%= form.text_field :url, class: 'wpcf7-form-control wpcf7-text', placeholder: 'Enter your website URL' %>
        <% if @speed_test.errors[:url].any? %>
          <span class="wpcf7-not-valid-tip" aria-hidden="true">This field must be a URL.</span>
        <% end %>
      </span>
    </div>
    <div class="col-lg-6 xs-mb-4">
      <span class="wpcf7-form-control-wrap your-email">
        <%= form.text_field :email, class: 'wpcf7-form-control wpcf7-text', placeholder: 'Enter your email address' %>
        <% if @speed_test.errors[:email].any? %>
          <span class="wpcf7-not-valid-tip" aria-hidden="true">This field must be an email.</span>
        <% end %>
      </span>
    </div>
    <div class="col-lg-12">
      <%= form.submit 'Start Test Now', class: "wpcf7-form-control wpcf7-submit" %>
    </div>
  </div>
  <% if @speed_test.errors.any? %>
    <div class="wpcf7-response-output" aria-hidden="true">
      One or more fields have an error. Please check and try again.
    </div>
  <% end %>
<% end %>

app/views/speed_tests/_refresh_or_download.html.erb
<div id="refresh-or-download">
  <% if @speed_test.done? %>
    <%= link_to "Download your report", speed_test_path(@speed_test, format: :pdf) %>
  <% else %>
    Processing results for <%= @speed_test.url %>
    <br>
    Status: <%= @speed_test.status_text %>
    <span class="ajax-loader" style="visibility: inherit;"></span>
  <% end %>
</div>

app/views/speed_tests/create.js.erb
Turbolinks.visit("<%= speed_test_path(@speed_test) %>")

app/views/speed_tests/error.js.erb
document.querySelector('#main-form').insertAdjacentHTML("afterend", "<%= j render('form') %>");
document.querySelector('#main-form').remove();

app/views/speed_tests/new.html.erb
<%= form_with model: @speed_test, local: false do |form| %>
  <%= form.text_field :url %>
  <%= form.text_field :email %>
  <%= form.submit %>
<% end %>

app/views/speed_tests/show.html.erb
<div class="elementor-element elementor-element-658973ad elementor-widget elementor-widget-xs-heading" data-id="658973ad" data-element_type="widget" data-settings="{&quot;ekit_we_effect_on&quot;:&quot;none&quot;}" data-widget_type="xs-heading.default">
  <div class="elementor-widget-container">
    <div class="xs-heading text-left">
      <h3 class="section-subtitle">Check Speed Performance</h3>
      <h2 class="section-title">How quickly does your <span>website </span> load?</h2>
    </div>
  </div>
</div>
<div class="elementor-element elementor-element-19f39ad5 elementor-widget elementor-widget-shortcode" data-id="19f39ad5" data-element_type="widget" data-settings="{&quot;_animation&quot;:&quot;none&quot;,&quot;ekit_we_effect_on&quot;:&quot;none&quot;}" data-widget_type="shortcode.default">
  <div class="elementor-widget-container">
    <div class="elementor-shortcode"><div role="form" class="wpcf7" id="wpcf7-f776-p782-o1" lang="en-US" dir="ltr">
      <div class="screen-reader-response"><p role="status" aria-live="polite" aria-atomic="true"></p> <ul></ul></div>
        <%= render 'refresh_or_download' %>
        <script>
          window.setTimeout(function(){
            document.querySelector('#sync').click();
          }, 3000)
        </script>
        <%= link_to "", speed_test_path(@speed_test), remote: true, style: 'display: none;', id: 'sync' %>
      </div>
    </div>
  </div>
</div>

app/views/speed_tests/show.js.erb
document.querySelector('#refresh-or-download').insertAdjacentHTML("afterend", "<%= j render('refresh_or_download') %>");
document.querySelector('#refresh-or-download').remove();
if (document.querySelector('#refresh-or-download').innerText != 'Download your report') {
  window.setTimeout(function(){
    window.document.querySelector('#sync').click();
  }, 3000)
}